# Generated by Django 3.2.12 on 2025-06-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='decription',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
