# Generated by Django 3.2.12 on 2025-06-15 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='decription',
            new_name='description',
        ),
    ]
